prefixes:
  feat: 🚀 Features
  fix: 🔧 Bug Fixes
  docs: 📖 Documentation
  doc: 📖 Documentation
  perf: ⚡️ Performance
  refactor: ✨ Refactor
  style: 🎨 Styling
  test: 🧪 Testing
  chore: Miscellaneous Tasks
  build: Miscellaneous Tasks
  deps: Miscellaneous Tasks
  ci: false
  revert: false
scopes:
  pLugin: Plugin
  server: Server
  terraform: Terraform
  "": Misc
titleVersionPrefix: remove
intialVersion: v2.1.0