name: ci-plugin-version-update
on:
  workflow_call:
    inputs:
      commit-sha:
        description: 'Commit SHA'
        required: true
        type: string

jobs:
 update-version:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: plugin
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update version
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.event.inputs.commit-sha }})
          current_version=$(awk '/version: [0-9]+\.[0-9]+\.[0-9]+/{print $2}' plugin/public/reearth.yml)
          if [[ $commit_message == *"major"* ]]; then
            new_version=$(awk -F '.' '{print $1 "." $2+1".0"}' <<< $current_version)
          elif [[ $commit_message == *"minor"* ]]; then
            new_version=$(awk -F '.' '{print $1 "." $2 "." $3+1}' <<< $current_version)
          else
            echo "Plugin related commit message must contain 'major' or 'minor'."
            exit 1
          fi
          sed -i "s/$current_version/$new_version/" plugin/public/reearth.yml
      - name: Commit and push changes
        run: |
          git add plugin/public/reearth.yml
          git commit -m "Update version"
          git push
