name: ci-tools
on:
  workflow_call:
jobs:
  ci-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: tools -> tools/target
      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: tools
      - name: test
        working-directory: tools
        run: cargo test --all

  ci-tools-build:
    needs: ci-tools
    name: ci-server-build - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: plateau-view-tool.exe
            name: plateau-view-tool-Windows-x86_64.zip

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: plateau-view-tool
            name: plateau-view-tool-Darwin-x86_64.tar.gz

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: tools -> tools/target
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
          working-directory: tools
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform.name }}
          path: tools/target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
          if-no-files-found: error
