name: ci-worker
on:
  workflow_call:
env:
  GO_VERSION: "1.21"
jobs:
  ci-worker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: worker
          args: --timeout=5m
  ci-worker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: worker/go.sum
      - name: test
        working-directory: worker
        run: go test ./... -v -race -tags draco
  ci-worker-test-index:
    runs-on: ubuntu-latest
    steps:
      - name: "indexer test: is testdata available"
        id: testdata
        run: echo $TESTDATA >> $GITHUB_OUTPUT
        env:
          TESTDATA: ${{ secrets.TESTDATA && 'testdata=1' || 'testdata=' }}
      - uses: actions/checkout@v3
        if: steps.testdata.outputs.testdata
      - uses: actions/setup-go@v4
        if: steps.testdata.outputs.testdata
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: worker/go.sum
      - name: "indexer test: download test 3D Tiles data"
        if: steps.testdata.outputs.testdata
        working-directory: worker
        run: curl -O $TESTDATA && mkdir -p searchindex/indexer/testdata && unzip -d searchindex/indexer/testdata "${TESTDATA##*/}"
        env:
          TESTDATA: ${{ secrets.TESTDATA }}
      - name: "indexer test: run indexer test"
        if: steps.testdata.outputs.testdata
        working-directory: worker
        run: go test ./searchindex/indexer -v -tags draco
      - name: "indexer test: list result files"
        if: steps.testdata.outputs.testdata
        working-directory: worker
        run: ls searchindex/indexer/testdata/result
      - name: "indexer test: cat resultsData.csv"
        if: steps.testdata.outputs.testdata
        working-directory: worker
        run: cat searchindex/indexer/testdata/result/resultsData.csv
