name: ci
on:
  push:
    branches: [main]
  pull_request:
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      plugin: ${{ steps.plugin.outputs.any_changed }}
      server: ${{ steps.server.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: changed files for plugin
        id: plugin
        uses: tj-actions/changed-files@v36
        with:
          files: |
            plugin
            .github/workflows/ci-plugin.yml
      - name: changed files for server
        id: server
        uses: tj-actions/changed-files@v36
        with:
          files: |
            server
            .github/workflows/ci.yml
            .github/workflows/ci-server.yml
            .github/workflows/build-server.yml
            .github/workflows/deploy-server-dev.yml
            .github/workflows/deploy-server-prod.yml
  ci-plugin:
    needs: prepare
    if: needs.prepare.outputs.plugin == 'true'
    uses: ./.github/workflows/ci-plugin.yml
  ci-server:
    needs: prepare
    if: needs.prepare.outputs.server == 'true'
    uses: ./.github/workflows/ci-server.yml
  ci:
    runs-on: ubuntu-latest
    needs:
      - ci-plugin
      - ci-server
    if: '!failure()'
    steps:
      - run: echo OK
  build-server:
    needs: ci-server
    if: success() && github.event_name == 'push' && github.ref_name == 'main'
    uses: ./.github/workflows/build-server.yml
  deploy-server-dev:
    needs: build-server
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: deploy-server-dev
