name: ⭐️ Deploy CMS dev
on:
  workflow_dispatch:
env:
  GCS_DEST: gs://cms-plateau-dev
  CMS_IMAGE_NAME: reearth/reearth-cms:rc
  CMS_IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/reearth-plateauview/reearth-cms:latest
  CMS_IMAGE_NAME_GCP: asia.gcr.io/reearth-plateau-dev/reearth-cms:latest
  WORKER_IMAGE_NAME: reearth/reearth-cms:rc
  WORKER_IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/reearth-plateauview/reearth-cms:latest
  WORKER_IMAGE_NAME_GCP: asia.gcr.io/reearth-plateau-dev/reearth-cms:latest
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/reearth-plateau-dev/locations/global/workloadIdentityPools/github-actions-oidc/providers/github-provider
  GCP_SERVICE_ACCOUNT: reearth-plateau-github-oidc@reearth-development.iam.gserviceaccount.com
  GCP_REGION: asia-northeast1
concurrency:
  group: ${{ github.workflow }}
jobs:

  deploy_web:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_REEARTH_DEV }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Download reearth-cms-web
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: reearth/reearth-cms
          version: tags/rc
          file: web/reearth-cms-web_rc.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract
        run: mv reearth-cms-web{_rc,}.tar.gz && tar -xvf reearth-cms-web.tar.gz
      - name: Deploy
        run: gsutil -m -h "Cache-Control:no-store" rsync -x "^reearth_config\\.json$" -dr reearth-cms-web/ ${{ env.GCS_DEST }}
      - name: Save as artifact
        uses: actions/upload-artifact@v2
        with:
          name: reearth-cms-web
          path: reearth-cms-web.tar.gz
  deploy_server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Configure docker
        run: gcloud auth configure-docker --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull docker images
        run: docker pull $CMS_IMAGE_NAME && docker pull $WORKER_IMAGE_NAME
      - name: Tag docker images
        run: docker tag $CMS_IMAGE_NAME $CMS_IMAGE_NAME_GHCR && docker tag $CMS_IMAGE_NAME $CMS_IMAGE_NAME_GCP && docker tag $WORKER_IMAGE_NAME $WORKER_IMAGE_NAME_GHCR && docker tag $WORKER_IMAGE_NAME $WORKER_IMAGE_NAME_GCP
      - name: Push docker images
        run: docker push $CMS_IMAGE_NAME_GHCR && docker push $CMS_IMAGE_NAME_GCP && docker push $WORKER_IMAGE_NAME_GHCR && docker push $WORKER_IMAGE_NAME_GCP
      - name: Deploy
        run: |
          gcloud run deploy reearth-cms-api \
            --image $CMS_IMAGE_NAME_GCP \
            --region $GCP_REGION \
            --platform managed \
            --quiet
          gcloud run deploy reearth-cms-worker \
            --image $WORKER_IMAGE_NAME_GCP \
            --region $GCP_REGION \
            --platform managed \
            --quiet
