name: ⭐️ Deploy PLATEAU worker dev
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      use_local:
        type: string
env:
  IMAGE: ghcr.io/eukarya-inc/reearth-plateauview/plateauview-api-worker:latest
  IMAGE_GCP: asia.gcr.io/reearth-plateau-dev/plateauview-api-worker:latest
  GCP_SERVICE_ACCOUNT: github-cicd-oidc@reearth-plateau-dev.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/383489516390/locations/global/workloadIdentityPools/github-actions-oidc/providers/github-provider
  GCP_REGION: asia-northeast1
concurrency:
  group: ${{ github.workflow }}
jobs:
  deploy_worker:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/reearth-plateauview'
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Configure docker
        run: gcloud auth configure-docker --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download worker arfiacts
        uses: dawidd6/action-download-artifact@v2
        if: inputs.use_local != 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yml
          workflow_conclusion: success
          branch: geospatialjpv3
          name: plateauview-api-worker
          check_artifacts: true
      - name: Download worker arfiacts
        if: inputs.use_local == 'true'
        uses: actions/download-artifact@v2
        with:
          name: plateauview-api-worker
      - name: Unpack docker image
        run: docker load < plateauview-api-worker.tar.gz
      - name: docker push
        run: |
          docker tag $IMAGE $IMAGE_GCP && \
          docker push $IMAGE &&
          docker push $IMAGE_GCP
