name: ⭐️ Deploy PLATEAU Server dev
on:
  workflow_run:
    workflows: [build-server]
    types: [completed]
    branches: [main]
env:
  IMAGE: ghcr.io/eukarya-inc/plateauview-api:latest
  IMAGE_GCP: asia.gcr.io/reearth-plateau-dev/plateauview-api:latest
  GCP_SERVICE_ACCOUNT:  github-cicd-oidc@reearth-plateau-dev.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/383489516390/locations/global/workloadIdentityPools/github-actions-oidc/providers/github-provider
  GCP_REGION: asia-northeast1
jobs:
  deploy_server:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'failure' && github.event.repository.full_name == 'eukarya-inc/reearth-plateauview' && github.event.workflow_run.head_branch == 'main'
    permissions:
      contents: read
      id-token: write
      packages: read
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Configure docker
        run: gcloud auth configure-docker --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download server arfiacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-server.yml
          workflow_conclusion: success
          branch: main
          name: plateauview-api
          check_artifacts: true
      - name: Unpack docker image
        run: docker load < plateauview-api.tar.gz
      - name: docker push
        run: |
          docker tag $IMAGE $IMAGE_GCP && \
          docker push $IMAGE &&
          docker push $IMAGE_GCP
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy plateauview-api \
            --image $IMAGE_GCP \
            --region $GCP_REGION \
            --platform managed \
            --quiet
