name: ci-plugin-version-update
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: choice
        default: minor
        options:
          - patch
          - minor

jobs:
  update-version:
    name: Update Version and release
    runs-on: ubuntu-latest
    steps:
      - name: Set up git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global pull.rebase false
      - name: Checkout code
        uses: actions/checkout@v3
      - id: changelog
        name: Generate CHANGELOG
        uses: reearth/changelog-action@main
        with:
          version: ${{ github.event.inputs.version }}
          repo: ${{ github.repository }}
          config: .github/changelog.yml
          latest: CHANGELOG_latest.md
      - name: Upload latest CHANGELOG
        uses: actions/upload-artifact@v3
        with:
          name: changelog-${{ steps.changelog.outputs.version }}
          path: CHANGELOG_latest.md
      - name: Extract non-"v" part of version
        id: version
        env:
            TAG: ${{ steps.changelog.outputs.version }}
        run: |
          new_version=$(echo "$TAG" | sed 's/^v//')
          echo "::set-output name=new_version::$new_version"
      - name: Update version
        env:
            VER: ${{ steps.version.outputs.new_version }}
        run: |
          current_version=$(awk '/version: [0-9]+\.[0-9]+\.[0-9]+/{print $2}' plugin/public/reearth.yml)
          sed -i "s/$current_version/$VER/" plugin/public/reearth.yml      
      - name: Commit and push changes
        env:
         TAG: ${{ steps.changelog.outputs.version }}
        run: |
          rm CHANGELOG_latest.md
          git add CHANGELOG.md plugin/public/reearth.yml
          git commit -m "chore(plugin): update plugin version to $TAG"
          git push --atomic origin main $TAG
