on:
  pull_request:
env:
  IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/reearth-plateauview/reearth:latest
  IMAGE_NAME_HUB: eukarya/plateauview2/reearth:latest
  CMS_IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/reearth-plateauview/reearth-cms:latest
  CMS_IMAGE_NAME_HUB: eukarya/plateauview2/reearth-cms:latest
  WORKER_IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/reearth-plateauview/reearth-cms-worker:latest
  WORKER_IMAGE_NAME_HUB: eukarya/plateauview2/reearth-cms-worker:latest
  SIDECAR_IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/reearth-plateauview/plateauview-api:latest
  SIDECAR_IMAGE_NAME_HUB: eukarya/plateauview2/sidecar:latest
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: |
          docker pull $IMAGE_NAME_GHCR
          docker pull $CMS_IMAGE_NAME_GHCR
          docker pull $WORKER_IMAGE_NAME_GHCR
          docker pull $SIDECAR_IMAGE_NAME_GHCR
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push image
        run: docker tag $IMAGE_NAME_GHCR $IMAGE_NAME_HUB && docker push $IMAGE_NAME_HUB
      - name: Push cms image
        run: docker tag $CMS_IMAGE_NAME_GHCR $CMS_IMAGE_NAME_HUB && docker push $CMS_IMAGE_NAME_HUB
      - name: Push cms worker image
        run: docker tag $WORKER_IMAGE_NAME_GHCR $WORKER_IMAGE_NAME_HUB && docker push $WORKER_IMAGE_NAME_HUB
      - name: Push sidecar image
        run: docker tag $SIDECAR_IMAGE_NAME_GHCR $SIDECAR_IMAGE_NAME_HUB && docker push $SIDECAR_IMAGE_NAME_HUB
